const ENIVROMENT_VARIABLES = {};

const { PORT, NODE_ENV, SECRET_KEY, CORS_ORIGIN, DBURI, API_TYPE, JWT_SECRET } = process.env;

ENIVROMENT_VARIABLES.SECRET_KEY = SECRET_KEY || "veri $ecret K#y";
ENIVROMENT_VARIABLES.PORT = PORT || 8080;
ENIVROMENT_VARIABLES.NODE_ENV = NODE_ENV || "development";
ENIVROMENT_VARIABLES.CORS_ORIGIN = CORS_ORIGIN || "http://localhost:3000";
ENIVROMENT_VARIABLES.DBURI = DBURI || "mongodb://localhost:27017/boxes";
ENIVROMENT_VARIABLES.API_TYPE = API_TYPE || "REST";
ENIVROMENT_VARIABLES.JWT_SECRET = JWT_SECRET || "somesupersecretkey";

module.exports = ENIVROMENT_VARIABLES;